### ISSUE TITLE
failed on macos 12 with msg level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""

### ISSUE THREAD

**Issue by wencaiwulue** [crazy-max/ghaction-setup-docker#108]
### Behaviour
error with message 
```text
   time="2024-09-22T03:44:34Z" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/runner/.lima/docker-actions-toolkit/serial*.log\")"
  time="2024-09-22T03:44:34Z" level=info msg="SSH Local Port: 49177"
  time="2024-09-22T03:44:34Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
  time="2024-09-22T03:44:44Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
```

setup docker on macos12 but failed, tried use 
```yaml
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        uses: crazy-max/ghaction-setup-docker@v3
        env:
          LIMA_START_ARGS: --vm-type vz
```
reference here
https://github.com/abiosoft/colima/issues/913#issuecomment-1849708119

but not work

```text
  time="2024-09-22T03:44:00Z" level=warning msg="`--vm-type` is not applicable to an existing instance (Hint: create a new instance with `limactl create --vm-type=vz --name=NAME`)"
```

#### Steps to reproduce this issue

1. 
2.
3.

#### Expected behaviour

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead

### Configuration

* Repository URL (if public): https://github.com/kubenetworks/kubevpn
* Build URL (if public): https://github.com/kubenetworks/kubevpn/actions/workflows/test.yml

```yml
# paste your YAML workflow file here and remove sensitive data
  macos:
    runs-on: macos-12
    needs: [ "image" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
          check-latest: true
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        env:
          LIMA_START_ARGS: --vm-type vz

      - name: Install minikube
        run: |
          set -x
          docker version
          brew install minikube
          minikube start --driver=docker
          kubectl get pod -A -o wide
          minikube kubectl -- get pod -A -o wide
```

### Logs

```text
::group::QEMU version
QEMU version
::group::Starting lima instance
Starting lima instance
  ##[debug]Exec.exec: limactl start --name=docker-actions-toolkit --vm-type vz 
  /usr/local/bin/limactl start --name=docker-actions-toolkit --vm-type vz
  time="2024-09-22T03:44:00Z" level=warning msg="provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:00Z" level=info msg="Using the existing instance \"docker-actions-toolkit\""
  time="2024-09-22T03:44:00Z" level=warning msg="`--vm-type` is not applicable to an existing instance (Hint: create a new instance with `limactl create --vm-type=vz --name=NAME`)"
  time="2024-09-22T03:44:00Z" level=warning msg="provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:00Z" level=info msg="Starting the instance \"docker-actions-toolkit\" with VM driver \"qemu\""
  time="2024-09-22T03:44:01Z" level=info msg="QEMU binary \"/usr/local/bin/qemu-system-x86_64\" seems properly signed with the \"com.apple.security.hypervisor\" entitlement"
  time="2024-09-22T03:44:01Z" level=warning msg="provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:01Z" level=info msg="Attempting to download the image" arch=x86_64 digest="sha256:054db2d88c454bb0ad8dfd8883955e3946b57d2b0bf0d023f3ade3c93cdd14e5" location="https://cloud-images.ubuntu.com/releases/22.04/release-20231026/ubuntu-22.04-server-cloudimg-amd64.img"
  Downloading the image (ubuntu-22.04-server-cloudimg-amd64.img)
  111.72 MiB / 641.12 MiB (17.43%) ? p/s
  251.25 MiB / 641.12 MiB (39.19%) 27.91 MiB/s
  356.02 MiB / 641.12 MiB (55.53%) 27.47 MiB/s
  470.45 MiB / 641.12 MiB (73.38%) 27.17 MiB/s
  556.22 MiB / 641.12 MiB (86.76%) 26.52 MiB/s
  640.92 MiB / 641.12 MiB (99.97%) 25.91 MiB/s
  641.12 MiB / 641.12 MiB (100.00%) 25.64 MiB/stime="2024-09-22T03:44:32Z" level=info msg="Downloaded the image from \"[https://cloud-images.ubuntu.com/releases/22.04/release-20231026/ubuntu-22.04-server-cloudimg-amd64.img\](https://cloud-images.ubuntu.com/releases/22.04/release-20231026/ubuntu-22.04-server-cloudimg-amd64.img/)""
  time="2024-09-22T03:44:32Z" level=warning msg="[hostagent] provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:32Z" level=warning msg="[hostagent] provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:32Z" level=warning msg="[hostagent] provisioning scripts should not reference the LIMA_CIDATA variables"
  time="2024-09-22T03:44:33Z" level=info msg="[hostagent] hostagent socket created at /Users/runner/.lima/docker-actions-toolkit/ha.sock"
  time="2024-09-22T03:44:34Z" level=info msg="[hostagent] Using system firmware (\"/usr/local/share/qemu/edk2-x86_64-code.fd\")"
  time="2024-09-22T03:44:34Z" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/runner/.lima/docker-actions-toolkit/serial*.log\")"
  time="2024-09-22T03:44:34Z" level=info msg="SSH Local Port: 49177"
  time="2024-09-22T03:44:34Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
  time="2024-09-22T03:44:44Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
```

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Seems to happen on macos-13 runners as well: https://github.com/docker/actions-toolkit/issues/455

**Comment by crazy-max** [comment]
This is an issue with QEMU 9.1.0, works fine with QEMU 9.0.2. As a workaround you can add this step before setting up docker similar to https://github.com/crazy-max/ghaction-setup-docker/pull/112/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR40-R44:

```yaml
      -
        # https://github.com/crazy-max/ghaction-setup-docker/issues/108
        name: Set up QEMU
        uses: docker/actions-toolkit/.github/actions/macos-setup-qemu@19ca9ade20f5da695f76a10988d6532058575f82
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
```
