### ISSUE TITLE
Intermittent Colima error on setup

### ISSUE THREAD

**Issue by verdverm** [crazy-max/ghaction-setup-docker#18]
![image](https://github.com/crazy-max/ghaction-setup-docker/assets/1390600/fe28e3f4-3de0-4f8e-b393-60e0aa842552)

- https://github.com/hofstadter-io/hof/actions/runs/5885331165/job/15962430814
- https://github.com/hofstadter-io/hof/actions/runs/5885331165/job/15961602949

It's intermittent, not every build hits this issue

Build step: https://github.com/hofstadter-io/hof/blob/_dev/.github/workflows/hof.yml#L58

**Comment by crazy-max** [comment]
It looks related to https://github.com/abiosoft/colima/issues/746. Can you try updating QEMU with `brew reinstall -f --force-bottle qemu` in a step right before setting up Docker?

**Comment by crazy-max** [comment]
I repro as well: https://github.com/crazy-max/ghaction-setup-docker/actions/runs/5888454932/job/15969694660?pr=17#step:3:216

**Comment by verdverm** [comment]
not fixing it for me: https://github.com/hofstadter-io/hof/actions/runs/5898945057/job/16000752109

If this is just upstream, feel free to close this issue

**Comment by crazy-max** [comment]
@verdverm Latest release should fix your issue, see https://github.com/crazy-max/ghaction-setup-docker#macos-qemustderr-qemu-system-x86_64-unknown-error for the workaround to apply.

**Comment by verdverm** [comment]
Thanks @crazy-max, I had switched over to some manual configary that did the signing step manually. Glad to switch back, pipeline is cleaner.

Along the way, I ended up with `colima start --cpu 3 --memory 10 --disk 12` Is there any way to set some of these values?

I have 3 container pull & starts that take multiple minutes. They aren't that big. Any ideas why this is so much slower on mac than ubu worker? Is this more than the emulation at play (and docker things take longer on mac everywhere, not just GHA)?

![image](https://github.com/crazy-max/ghaction-setup-docker/assets/1390600/e05d33a9-a6ab-4b49-ad59-a7b224862c22)

**Comment by crazy-max** [comment]
> Along the way, I ended up with `colima start --cpu 3 --memory 10 --disk 12` Is there any way to set some of these values?

I think we could provide env vars that could be injected in colima config like `COLIMA_CPU`, `COLIMA_MEMORY`, ...

> Any ideas why this is so much slower on mac than ubu worker?

Yes atm on macOS runner it's using QEMU so this might linked to emulation and also 9p mount that can be quite slow if your context is huge. With `macos-13` runner we could potentially switch to macOS virtualization framework (vz) and virtiofs instead of 9p as mount type. I have started something in https://github.com/docker/actions-toolkit/pull/157.

Do you have a link to the workflow run for me to check?

**Comment by crazy-max** [comment]
> I think we could provide env vars that could be injected in colima config like `COLIMA_CPU`, `COLIMA_MEMORY`, ...

Or we could just have a `COLIMA_CONFIG` env var that would merged with the one I generate on my side. Would look like this:

```yaml
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
        env:
          COLIMA_CONFIG: |
            cpu: 3
            memory: 10
            disk: 12
            mounts:
              - location: ~/secrets
                writable: false
              - location: ~/projects
                writable: true
```

WDYT?
